// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/data/data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyVersions struct {
	Versions             []int64  `protobuf:"varint,1,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyVersions) Reset()         { *m = KeyVersions{} }
func (m *KeyVersions) String() string { return proto.CompactTextString(m) }
func (*KeyVersions) ProtoMessage()    {}
func (*KeyVersions) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{0}
}

func (m *KeyVersions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyVersions.Unmarshal(m, b)
}
func (m *KeyVersions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyVersions.Marshal(b, m, deterministic)
}
func (m *KeyVersions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyVersions.Merge(m, src)
}
func (m *KeyVersions) XXX_Size() int {
	return xxx_messageInfo_KeyVersions.Size(m)
}
func (m *KeyVersions) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyVersions.DiscardUnknown(m)
}

var xxx_messageInfo_KeyVersions proto.InternalMessageInfo

func (m *KeyVersions) GetVersions() []int64 {
	if m != nil {
		return m.Versions
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyVersions)(nil), "KeyVersions")
}

func init() { proto.RegisterFile("protos/data/data.proto", fileDescriptor_492be2f0ffbab25c) }

var fileDescriptor_492be2f0ffbab25c = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x49, 0x2c, 0x49, 0x04, 0x13, 0x7a, 0x60, 0x01, 0x25, 0x4d, 0x2e, 0x6e,
	0xef, 0xd4, 0xca, 0xb0, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0xbc, 0x62, 0x21, 0x29, 0x2e, 0x8e, 0x32,
	0x28, 0x5b, 0x82, 0x51, 0x81, 0x59, 0x83, 0x39, 0x08, 0xce, 0x4f, 0x62, 0x03, 0xeb, 0x30, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x07, 0x25, 0xeb, 0x57, 0x4b, 0x00, 0x00, 0x00,
}
