[[override]]
  name = "github.com/golang/protobuf"
  version = "=v1.3.1"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=v0.30.2"

[prune]
  go-tests = true
  unused-packages = true