[[constraint]]
  name = "github.com/ndidplatform/smart-contract"
  version = "=v1.0.0"
 
[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=v0.26.4"

[prune]
  go-tests = true
  unused-packages = true