[[constraint]]
  name = "github.com/tendermint/iavl"
  version = "0.11.0"

[[constraint]]
  name = "github.com/ndidplatform/smart-contract"
  version = "0.13.0"
 
[[override]]
  name = "github.com/tendermint/tendermint"
  version = "0.26.3"

[prune]
  go-tests = true
  unused-packages = true