[[constraint]]
  name = "github.com/ndidplatform/smart-contract"
  version = "=v2.0.0"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "=v0.3.1"
  
[prune]
  go-tests = true
  unused-packages = true