[[constraint]]
  name = "github.com/ndidplatform/smart-contract"
  version = "=v2.0.0"
 
[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=v0.30.2"
  
[prune]
  go-tests = true
  unused-packages = true