// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/dataV2/dataV2.proto

package dataV2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeDetail struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName             string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal               float64  `protobuf:"fixed64,5,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal               float64  `protobuf:"fixed64,6,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	Mq                   []*MQ    `protobuf:"bytes,7,rep,name=mq,proto3" json:"mq,omitempty"`
	Active               bool     `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	ProxyNodeId          string   `protobuf:"bytes,9,opt,name=proxy_node_id,json=proxyNodeId,proto3" json:"proxy_node_id,omitempty"`
	ProxyConfig          string   `protobuf:"bytes,10,opt,name=proxy_config,json=proxyConfig,proto3" json:"proxy_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDetail) Reset()         { *m = NodeDetail{} }
func (m *NodeDetail) String() string { return proto.CompactTextString(m) }
func (*NodeDetail) ProtoMessage()    {}
func (*NodeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_d788542f3fe2e8c7, []int{0}
}

func (m *NodeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDetail.Unmarshal(m, b)
}
func (m *NodeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDetail.Marshal(b, m, deterministic)
}
func (m *NodeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDetail.Merge(m, src)
}
func (m *NodeDetail) XXX_Size() int {
	return xxx_messageInfo_NodeDetail.Size(m)
}
func (m *NodeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDetail proto.InternalMessageInfo

func (m *NodeDetail) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *NodeDetail) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *NodeDetail) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeDetail) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *NodeDetail) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *NodeDetail) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

func (m *NodeDetail) GetMq() []*MQ {
	if m != nil {
		return m.Mq
	}
	return nil
}

func (m *NodeDetail) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *NodeDetail) GetProxyNodeId() string {
	if m != nil {
		return m.ProxyNodeId
	}
	return ""
}

func (m *NodeDetail) GetProxyConfig() string {
	if m != nil {
		return m.ProxyConfig
	}
	return ""
}

type MQ struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MQ) Reset()         { *m = MQ{} }
func (m *MQ) String() string { return proto.CompactTextString(m) }
func (*MQ) ProtoMessage()    {}
func (*MQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_d788542f3fe2e8c7, []int{1}
}

func (m *MQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MQ.Unmarshal(m, b)
}
func (m *MQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MQ.Marshal(b, m, deterministic)
}
func (m *MQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MQ.Merge(m, src)
}
func (m *MQ) XXX_Size() int {
	return xxx_messageInfo_MQ.Size(m)
}
func (m *MQ) XXX_DiscardUnknown() {
	xxx_messageInfo_MQ.DiscardUnknown(m)
}

var xxx_messageInfo_MQ proto.InternalMessageInfo

func (m *MQ) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *MQ) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type NamespaceList struct {
	Namespaces           []*Namespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NamespaceList) Reset()         { *m = NamespaceList{} }
func (m *NamespaceList) String() string { return proto.CompactTextString(m) }
func (*NamespaceList) ProtoMessage()    {}
func (*NamespaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d788542f3fe2e8c7, []int{2}
}

func (m *NamespaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceList.Unmarshal(m, b)
}
func (m *NamespaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceList.Marshal(b, m, deterministic)
}
func (m *NamespaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceList.Merge(m, src)
}
func (m *NamespaceList) XXX_Size() int {
	return xxx_messageInfo_NamespaceList.Size(m)
}
func (m *NamespaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceList.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceList proto.InternalMessageInfo

func (m *NamespaceList) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

type Namespace struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_d788542f3fe2e8c7, []int{3}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Namespace) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Namespace) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Request struct {
	RequestId            string         `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MinIdp               int64          `protobuf:"varint,2,opt,name=min_idp,json=minIdp,proto3" json:"min_idp,omitempty"`
	MinAal               float64        `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	MinIal               float64        `protobuf:"fixed64,4,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	RequestTimeout       int64          `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	IdpIdList            []string       `protobuf:"bytes,6,rep,name=idp_id_list,json=idpIdList,proto3" json:"idp_id_list,omitempty"`
	DataRequestList      []*DataRequest `protobuf:"bytes,7,rep,name=data_request_list,json=dataRequestList,proto3" json:"data_request_list,omitempty"`
	RequestMessageHash   string         `protobuf:"bytes,8,opt,name=request_message_hash,json=requestMessageHash,proto3" json:"request_message_hash,omitempty"`
	ResponseList         []*Response    `protobuf:"bytes,9,rep,name=response_list,json=responseList,proto3" json:"response_list,omitempty"`
	Closed               bool           `protobuf:"varint,10,opt,name=closed,proto3" json:"closed,omitempty"`
	TimedOut             bool           `protobuf:"varint,11,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Purpose              string         `protobuf:"bytes,12,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Owner                string         `protobuf:"bytes,13,opt,name=owner,proto3" json:"owner,omitempty"`
	Mode                 int64          `protobuf:"varint,14,opt,name=mode,proto3" json:"mode,omitempty"`
	UseCount             int64          `protobuf:"varint,15,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	CreationBlockHeight  int64          `protobuf:"varint,16,opt,name=creation_block_height,json=creationBlockHeight,proto3" json:"creation_block_height,omitempty"`
	ChainId              string         `protobuf:"bytes,17,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d788542f3fe2e8c7, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Request) GetMinIdp() int64 {
	if m != nil {
		return m.MinIdp
	}
	return 0
}

func (m *Request) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *Request) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *Request) GetRequestTimeout() int64 {
	if m != nil {
		return m.RequestTimeout
	}
	return 0
}

func (m *Request) GetIdpIdList() []string {
	if m != nil {
		return m.IdpIdList
	}
	return nil
}

func (m *Request) GetDataRequestList() []*DataRequest {
	if m != nil {
		return m.DataRequestList
	}
	return nil
}

func (m *Request) GetRequestMessageHash() string {
	if m != nil {
		return m.RequestMessageHash
	}
	return ""
}

func (m *Request) GetResponseList() []*Response {
	if m != nil {
		return m.ResponseList
	}
	return nil
}

func (m *Request) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func (m *Request) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *Request) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Request) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Request) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Request) GetUseCount() int64 {
	if m != nil {
		return m.UseCount
	}
	return 0
}

func (m *Request) GetCreationBlockHeight() int64 {
	if m != nil {
		return m.CreationBlockHeight
	}
	return 0
}

func (m *Request) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type DataRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsIdList             []string `protobuf:"bytes,2,rep,name=as_id_list,json=asIdList,proto3" json:"as_id_list,omitempty"`
	MinAs                int64    `protobuf:"varint,3,opt,name=min_as,json=minAs,proto3" json:"min_as,omitempty"`
	RequestParamsHash    string   `protobuf:"bytes,4,opt,name=request_params_hash,json=requestParamsHash,proto3" json:"request_params_hash,omitempty"`
	AnsweredAsIdList     []string `protobuf:"bytes,5,rep,name=answered_as_id_list,json=answeredAsIdList,proto3" json:"answered_as_id_list,omitempty"`
	ReceivedDataFromList []string `protobuf:"bytes,6,rep,name=received_data_from_list,json=receivedDataFromList,proto3" json:"received_data_from_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d788542f3fe2e8c7, []int{5}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *DataRequest) GetAsIdList() []string {
	if m != nil {
		return m.AsIdList
	}
	return nil
}

func (m *DataRequest) GetMinAs() int64 {
	if m != nil {
		return m.MinAs
	}
	return 0
}

func (m *DataRequest) GetRequestParamsHash() string {
	if m != nil {
		return m.RequestParamsHash
	}
	return ""
}

func (m *DataRequest) GetAnsweredAsIdList() []string {
	if m != nil {
		return m.AnsweredAsIdList
	}
	return nil
}

func (m *DataRequest) GetReceivedDataFromList() []string {
	if m != nil {
		return m.ReceivedDataFromList
	}
	return nil
}

type Response struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	Aal                  float64  `protobuf:"fixed64,2,opt,name=aal,proto3" json:"aal,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	IdentityProof        string   `protobuf:"bytes,5,opt,name=identity_proof,json=identityProof,proto3" json:"identity_proof,omitempty"`
	PrivateProofHash     string   `protobuf:"bytes,6,opt,name=private_proof_hash,json=privateProofHash,proto3" json:"private_proof_hash,omitempty"`
	IdpId                string   `protobuf:"bytes,7,opt,name=idp_id,json=idpId,proto3" json:"idp_id,omitempty"`
	ValidProof           string   `protobuf:"bytes,8,opt,name=valid_proof,json=validProof,proto3" json:"valid_proof,omitempty"`
	ValidIal             string   `protobuf:"bytes,9,opt,name=valid_ial,json=validIal,proto3" json:"valid_ial,omitempty"`
	ValidSignature       string   `protobuf:"bytes,10,opt,name=valid_signature,json=validSignature,proto3" json:"valid_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d788542f3fe2e8c7, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *Response) GetAal() float64 {
	if m != nil {
		return m.Aal
	}
	return 0
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Response) GetIdentityProof() string {
	if m != nil {
		return m.IdentityProof
	}
	return ""
}

func (m *Response) GetPrivateProofHash() string {
	if m != nil {
		return m.PrivateProofHash
	}
	return ""
}

func (m *Response) GetIdpId() string {
	if m != nil {
		return m.IdpId
	}
	return ""
}

func (m *Response) GetValidProof() string {
	if m != nil {
		return m.ValidProof
	}
	return ""
}

func (m *Response) GetValidIal() string {
	if m != nil {
		return m.ValidIal
	}
	return ""
}

func (m *Response) GetValidSignature() string {
	if m != nil {
		return m.ValidSignature
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeDetail)(nil), "NodeDetail")
	proto.RegisterType((*MQ)(nil), "MQ")
	proto.RegisterType((*NamespaceList)(nil), "NamespaceList")
	proto.RegisterType((*Namespace)(nil), "Namespace")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("protos/dataV2/dataV2.proto", fileDescriptor_d788542f3fe2e8c7) }

var fileDescriptor_d788542f3fe2e8c7 = []byte{
	// 883 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x55, 0x51, 0x6f, 0xe4, 0x34,
	0x10, 0xd6, 0x26, 0x6d, 0x36, 0x99, 0xed, 0x6e, 0x5b, 0xb7, 0xbd, 0x33, 0xdc, 0x01, 0xcb, 0x4a,
	0x88, 0xd5, 0x09, 0x16, 0x54, 0x84, 0x84, 0xc4, 0x53, 0xb9, 0x13, 0xba, 0x15, 0xf4, 0xe8, 0x05,
	0xc4, 0x6b, 0xe4, 0xc6, 0x6e, 0xd7, 0xba, 0x24, 0x4e, 0x6d, 0x67, 0xdb, 0xfe, 0x29, 0x5e, 0x79,
	0xe2, 0x77, 0xf1, 0x7a, 0xf2, 0xd8, 0xd9, 0xe6, 0xa9, 0x9e, 0xef, 0x9b, 0x74, 0x3c, 0xf3, 0x7d,
	0xe3, 0x85, 0x4f, 0x5b, 0xad, 0xac, 0x32, 0xdf, 0x71, 0x66, 0xd9, 0xdf, 0xe7, 0xe1, 0xcf, 0x0a,
	0xc1, 0xc5, 0x3f, 0x11, 0xc0, 0x3b, 0xc5, 0xc5, 0x1b, 0x61, 0x99, 0xac, 0xc8, 0x67, 0x00, 0x6d,
	0x77, 0x5d, 0xc9, 0xb2, 0xf8, 0x20, 0x1e, 0xe9, 0x68, 0x3e, 0x5a, 0x66, 0x79, 0xe6, 0x91, 0xdf,
	0xc4, 0x23, 0x79, 0x05, 0xc7, 0x35, 0x33, 0x56, 0xe8, 0x62, 0x90, 0x15, 0x61, 0xd6, 0xa1, 0x27,
	0xae, 0x76, 0xb9, 0x2f, 0x20, 0x6b, 0x14, 0x17, 0x45, 0xc3, 0x6a, 0x41, 0x63, 0xcc, 0x49, 0x1d,
	0xf0, 0x8e, 0xd5, 0x82, 0x10, 0xd8, 0xd3, 0xaa, 0x12, 0x74, 0x0f, 0x71, 0x3c, 0x93, 0xe7, 0x30,
	0xae, 0xd9, 0x43, 0x21, 0x59, 0x45, 0xf7, 0xe7, 0xa3, 0xe5, 0x28, 0x4f, 0x6a, 0xf6, 0xb0, 0x66,
	0x55, 0x4f, 0x30, 0x56, 0xd1, 0x64, 0x47, 0x5c, 0xb0, 0x8a, 0x9c, 0x40, 0x54, 0xdf, 0xd1, 0xf1,
	0x3c, 0x5e, 0x4e, 0xce, 0xe3, 0xd5, 0xe5, 0xfb, 0x3c, 0xaa, 0xef, 0xc8, 0x33, 0x48, 0x58, 0x69,
	0xe5, 0x56, 0xd0, 0x74, 0x3e, 0x5a, 0xa6, 0x79, 0x88, 0xc8, 0x02, 0xa6, 0xad, 0x56, 0x0f, 0x8f,
	0x05, 0xde, 0x4a, 0x72, 0x9a, 0x61, 0xed, 0x09, 0x82, 0x6e, 0x04, 0x6b, 0x4e, 0xbe, 0x84, 0x03,
	0x9f, 0x53, 0xaa, 0xe6, 0x46, 0xde, 0x52, 0x18, 0xa4, 0xbc, 0x46, 0x68, 0xb1, 0x84, 0xe8, 0xf2,
	0x3d, 0x99, 0x41, 0x24, 0xdb, 0x30, 0x9f, 0x48, 0xb6, 0xae, 0x9f, 0x56, 0x69, 0x8b, 0xb3, 0x88,
	0x73, 0x3c, 0x2f, 0x7e, 0x86, 0xa9, 0xeb, 0xd5, 0xb4, 0xac, 0x14, 0xbf, 0x4b, 0x63, 0xc9, 0x2b,
	0x80, 0xa6, 0x07, 0x0c, 0x1d, 0xe1, 0xb5, 0x61, 0xb5, 0xcb, 0xc9, 0x07, 0xec, 0xa2, 0x84, 0x6c,
	0x47, 0x90, 0x97, 0x90, 0xed, 0xa8, 0x5e, 0x94, 0x1d, 0x40, 0xe6, 0x30, 0xe1, 0xc2, 0x94, 0x5a,
	0xb6, 0x56, 0xaa, 0x26, 0xc8, 0x31, 0x84, 0x06, 0x23, 0x89, 0x87, 0x23, 0x59, 0xfc, 0xb7, 0x07,
	0xe3, 0x5c, 0xdc, 0x75, 0xc2, 0x58, 0xa7, 0xbc, 0xf6, 0x47, 0x37, 0x9b, 0x50, 0x24, 0x20, 0x6b,
	0x8e, 0x1a, 0xc8, 0xa6, 0x90, 0xbc, 0x0d, 0x3d, 0x26, 0xb5, 0x6c, 0xd6, 0xbc, 0xed, 0x09, 0x27,
	0x4e, 0x1c, 0xc4, 0x91, 0xcd, 0x45, 0x50, 0xcd, 0x7d, 0xc1, 0x2a, 0x54, 0xd9, 0x13, 0x4e, 0xce,
	0xaf, 0xe1, 0xb0, 0xaf, 0x64, 0x65, 0x2d, 0x54, 0x67, 0x51, 0xef, 0x38, 0x9f, 0x05, 0xf8, 0x2f,
	0x8f, 0x92, 0xcf, 0x61, 0x22, 0x79, 0x5b, 0x48, 0x5e, 0x54, 0xd2, 0x58, 0x9a, 0xcc, 0x63, 0x77,
	0x27, 0xc9, 0xdb, 0x35, 0xc7, 0x79, 0xfe, 0x04, 0xc7, 0xce, 0xcb, 0x45, 0xff, 0xdf, 0x30, 0xcb,
	0xbb, 0xe1, 0x60, 0xf5, 0x86, 0x59, 0x16, 0x7a, 0xcb, 0x0f, 0xf9, 0x53, 0x80, 0x5f, 0x7e, 0x0f,
	0xa7, 0xfd, 0x47, 0xb5, 0x30, 0x86, 0xdd, 0x8a, 0x62, 0xc3, 0xcc, 0x06, 0x1d, 0x93, 0xe5, 0x24,
	0x70, 0x97, 0x9e, 0x7a, 0xcb, 0xcc, 0x86, 0xac, 0x60, 0xaa, 0x85, 0x69, 0x55, 0x63, 0x84, 0xaf,
	0x93, 0x61, 0x9d, 0x6c, 0x95, 0x07, 0x34, 0x3f, 0xe8, 0x79, 0xac, 0xf0, 0x0c, 0x92, 0xb2, 0x52,
	0x46, 0x70, 0xf4, 0x50, 0x9a, 0x87, 0xc8, 0x6d, 0x85, 0x6b, 0x9a, 0x17, 0xae, 0xed, 0x09, 0x52,
	0x29, 0x02, 0x7f, 0x74, 0x96, 0x50, 0x18, 0xb7, 0x9d, 0x6e, 0x95, 0x11, 0xf4, 0x00, 0x6f, 0xd2,
	0x87, 0xe4, 0x14, 0xf6, 0xd5, 0x7d, 0x23, 0x34, 0x9d, 0x22, 0xee, 0x03, 0xe7, 0xba, 0x5a, 0x71,
	0x41, 0x67, 0xde, 0x75, 0xee, 0xec, 0x0a, 0x74, 0x46, 0x14, 0xa5, 0xea, 0x1a, 0x4b, 0x0f, 0x91,
	0x48, 0x3b, 0x23, 0x5e, 0xbb, 0x98, 0x9c, 0xc3, 0x59, 0xa9, 0x05, 0x73, 0xa6, 0x28, 0xae, 0x2b,
	0x55, 0x7e, 0x28, 0x36, 0x42, 0xde, 0x6e, 0x2c, 0x3d, 0xc2, 0xc4, 0x93, 0x9e, 0xfc, 0xc5, 0x71,
	0x6f, 0x91, 0x22, 0x9f, 0x40, 0x5a, 0x6e, 0x18, 0x6a, 0x4f, 0x8f, 0xfd, 0xad, 0x30, 0x5e, 0xf3,
	0xc5, 0xff, 0x23, 0x98, 0x0c, 0xe6, 0xec, 0x3c, 0x64, 0x84, 0xde, 0xca, 0x52, 0x0c, 0x3c, 0x14,
	0x90, 0x35, 0x27, 0x2f, 0x01, 0x98, 0xd9, 0xc9, 0x19, 0xa1, 0x9c, 0x29, 0x33, 0x41, 0xcd, 0x33,
	0x48, 0xd0, 0x48, 0x06, 0x7d, 0x14, 0xe7, 0xfb, 0xce, 0x47, 0x86, 0xac, 0xe0, 0xa4, 0x97, 0xaa,
	0x65, 0x9a, 0xd5, 0xc6, 0x2b, 0xe5, 0x1f, 0x8e, 0xe3, 0x40, 0x5d, 0x21, 0x83, 0x42, 0x7d, 0x0b,
	0x27, 0xac, 0x31, 0xf7, 0x42, 0x0b, 0x5e, 0x0c, 0xaa, 0xed, 0x63, 0xb5, 0xa3, 0x9e, 0xba, 0xe8,
	0xab, 0xfe, 0x08, 0xcf, 0xb5, 0x28, 0x85, 0xdc, 0x0a, 0x5e, 0xa0, 0x99, 0x6e, 0xb4, 0xaa, 0x87,
	0x7e, 0x3b, 0xed, 0x69, 0xd7, 0xe8, 0xaf, 0x5a, 0xd5, 0xee, 0xb3, 0xc5, 0xbf, 0x11, 0xa4, 0xbd,
	0xf2, 0xe4, 0x08, 0x62, 0xe7, 0xf2, 0x11, 0xba, 0xdc, 0x1d, 0x1d, 0xe2, 0x16, 0x22, 0xf2, 0x08,
	0x63, 0x95, 0xf3, 0x83, 0xb1, 0xcc, 0x76, 0x26, 0x3c, 0x85, 0x21, 0x72, 0xab, 0x6d, 0xe4, 0x6d,
	0xc3, 0x6c, 0xa7, 0xfb, 0xd7, 0xf0, 0x09, 0x20, 0x5f, 0xc1, 0x4c, 0x72, 0xd1, 0x58, 0x69, 0x1f,
	0x8b, 0x56, 0x2b, 0x75, 0x83, 0x9b, 0x92, 0xe5, 0xd3, 0x1e, 0xbd, 0x72, 0x20, 0xf9, 0x06, 0x48,
	0xab, 0xe5, 0x96, 0x59, 0xe1, 0xb3, 0xfc, 0x88, 0x12, 0x4c, 0x3d, 0x0a, 0x0c, 0x66, 0xe2, 0x84,
	0xce, 0x20, 0xf1, 0x6b, 0x45, 0xc7, 0xde, 0x4c, 0xb8, 0x51, 0xe4, 0x0b, 0x98, 0x6c, 0x59, 0x25,
	0x79, 0x28, 0xe4, 0x57, 0x01, 0x10, 0xf2, 0x55, 0x5e, 0x40, 0xe6, 0x13, 0x5c, 0xb3, 0xfe, 0xf1,
	0x4c, 0x11, 0x08, 0x4b, 0xed, 0xc9, 0xa7, 0x6e, 0xfc, 0xe3, 0x39, 0x43, 0xf8, 0xcf, 0x1e, 0xbd,
	0x4e, 0xf0, 0x77, 0xe7, 0x87, 0x8f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xe1, 0xd0, 0x8f, 0x95,
	0x06, 0x00, 0x00,
}
